### ISSUE TITLE
Validating a normalized payload using the provided JSON schema does not work

### ISSUE THREAD

**Issue by hdelva** [smart-data-models/dataModel.Environment#13]
According to the [the main site](https://smartdatamodels.org/index.php/check-a-schema-validates-a-payload/), the best way to validate a payload is to simply use https://www.jsonschemavalidator.net/ in combination with the JSON schema files on Github. However, the [AirQualityObserved schema](https://raw.githubusercontent.com/smart-data-models/dataModel.Environment/master/AirQualityObserved/schema.json) only supports the keyValues representation -- which as far as I know, is the least important serialization format of NGSI-LD data. 

For instance, the schema file specifies:
```
"dateObserved": {
  "type": "string",
  "description": "Property. The date and time of this observation in ISO8601 UTCformat. Model:'https://schema.org/Text' "
}
```
Which conflicts with the current data example:
```
"dateObserved": {
  "type": "Property",
  "value": "2016-03-15T11:00:00/2016-03-15T12:00:00"
}
```
With the following error message:
```
Invalid Type. Expected String but got Object.
```

Would it be possible to provide schema files for both the keyvalues and the normalized formats? 
Additionally, it may be worth considering to use SHACL (or ShEx) instead of JSON Schema, as these languages contain useful LD-specific features that JSON Schema wasn't designed for.

**Comment by albertoabellagarcia** [comment]
1) Yes you're right the schema only validates the key values.
2) Bear in mind that we have two formats for normalized payloads, the NGSIv2 and NGSDI-LD which are substantially different. Therefore validating the normalized format means having 3 schemas, not 1 like we have currently. 
3) We are assessing if thanks to some automation process we could generate those 3 out of the key values. Otherwise, we would impose the contributors more than triple the effort to contribute. I believe in the excellent and powerful will of the volunteer contributors, however, it would be naive not to think that some of them would desist before completing the 3 schemas. (I have to thank many of them that struggle with the creation of the schema because their knowledge is more about the topic and not about data modeling or JSON schema).
4) Regarding SHACL and ShEx alternatives, are good recommendations. We use to survey the contributors periodically (once a month basically) so this would be one of the issues to address. 
Thank you very much for your comments-
