### ISSUE TITLE
Request for addition of attributes

### ISSUE THREAD

**Issue by manurag1234** [smart-data-models/dataModel.Environment#21]
Hi team,

Request you to please add "PM4", "TPC"(Total Particulate Counter) and "TSP"(Total suspended Particles) metric in in the airqualityObserved data model set

"pm4":{
	"type": "Integer",
	"value": 10
	},
"tpc":{
	"type": "Integer",
	"value": 10
	},
"tsp":{
	"type": "Integer",
	"value": 10
	}

**Comment by albertoabellagarcia** [comment]
That is interesting. The comment is that in order to extend the model you need to provide an extended version of the schema and one example showing the use. Please check the [contribution manual](https://bit.ly/contribution_manual). If you need more support check [this page](https://smartdatamodels.org/index.php/support/) with the support channels

**Comment by albertoabellagarcia** [comment]
do you need specific meeting about this contribution, please book it [here](https://calendly.com/smartdatamodels)

**Comment by albertoabellagarcia** [comment]
I see that you already made the PR. closing the issue
